version: '3.8'
services:
  backend:
    image: ms-sp-support-exchange-rate:latest
    build:
      context: .
    volumes:
      - ./docker-files/application.yml:/opt/application.yml
    ports:
      - "9091:9091"
    depends_on:
      - db
      - redis
  db:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis
    ports:
      - "6379:6379"
volumes:
  db: