server:
  port: 9092
  servlet:
    context-path: /ms-sp-support-exchange-rate/validar-tipocambio/v1

spring:
  codec:
    max-in-memory-size: 10MB
  application:
    name: ms-sp-support-exchange-rate-v1
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3307/reto_db
    username: root
    password: '123456'
    driverClassName: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect


log4j:
  logger:
    org:
      hibernate:
        SQL: debug
        type: trace
